### ISSUE TITLE
USB and UART options backwards

### ISSUE THREAD

**Issue by 0xen** [raspberrypi/pico-project-generator#12]
I believe the two USB stdio and UART are backward in the UI as when you select USB stdio you get 
pico_enable_stdio_usb(Project 0)

**Comment by JamesH65** [comment]
I've just tried this with the latest code and it seems to be correct. Are you using the GUI or command line?

**Comment by JamesH65** [comment]
hold on, tried again and wrong! Will check.

**Comment by JamesH65** [comment]
Fixed.
Please update to the latest version which contains a fix for this issue.
