### ISSUE TITLE
running from ram - projectName is undefined

### ISSUE THREAD

**Issue by alphathegeek** [raspberrypi/pico-project-generator#14]
when "run from ram" option is selected - projectName is undefined, it should be "params.projectName"

diff --git a/pico_project.py b/pico_project.py
index ea41f11..467c527 100755
--- a/pico_project.py
+++ b/pico_project.py
@@ -891,7 +891,7 @@ def GenerateCMake(folder, params):
 
     if params.wantRunFromRAM:
         file.write('# no_flash means the target is to run from RAM\n')
-        file.write('pico_set_binary_type(' + projectName + ' no_flash)\n\n')
+        file.write('pico_set_binary_type(' + params.projectName + ' no_flash)\n\n')
 
     # Console output destinations
     if params.wantUART:

**Comment by JamesH65** [comment]
Fixed
