### ISSUE TITLE
Generate C++ option for Pico Project Generator

### ISSUE THREAD

**Issue by nyh-workshop** [raspberrypi/pico-project-generator#20]
Some of us are using C++ for Pico SDK and need the team's support to add the Generate C++ option on that GUI (and also the command line)

**Comment by JamesH65** [comment]
Should be added fixed with latest commit. Currently simply makes the project a .cpp file rather than just .c

**Comment by Trance-Paradox** [comment]
I am not able to build the project currently when using c++ file. Upon building the build config files are just added in the build folder and anything isn't compiled.

**Comment by lurch** [comment]
Can you please provide more details? e.g. what OS are you using, what compiler are you using, what exact steps did you use, what command-line did you run, what error messages did you get, etc. etc.

**Comment by Trance-Paradox** [comment]
> Can you please provide more details? e.g. what OS are you using, what compiler are you using, what exact steps did you use, what command-line did you run, what error messages did you get, etc. etc.

OS - WINDOWS 10
Command Line - MS Build Tools
IDE - VScode
Toolchain - GNU arm embedded

I opened the Pico Project generator and select the following settings
![image](https://user-images.githubusercontent.com/54877610/121931699-96c5cf80-cd61-11eb-93ca-b89db71ea1cb.png)

An then opened vscode from ms build tools command line. But building the project in release mode in vscode just give make files and make config in build folder. Any of the compiled files aren't created. That is there is no uf2 or hex file present in build folder.
![image](https://user-images.githubusercontent.com/54877610/121932026-ffad4780-cd61-11eb-9183-55103c021088.png)

**Comment by lurch** [comment]
I see there's a `build.ninja` file in your screenshot - that's not right, and means you've missed one of the configuration steps. See the getting started guide https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf

**Comment by Trance-Paradox** [comment]
> I see there's a `build.ninja` file in your screenshot - that's not right, and means you've missed one of the configuration steps. See the getting started guide https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf

Of I think I got it. I was configuring the environment again and again instead of building. But as you can see the bottom bar of my vscode does not contain any build button. How can I make it appear in the button bar?

**Comment by lurch** [comment]
This is probably related to #32 and https://github.com/raspberrypi/pico-feedback/issues/134 
Unfortunately VS Code support is a low-priority task that we've not had enough spare time to deep-dive into.

It _should_ still work if you build from the command-line though?

**Comment by Trance-Paradox** [comment]
> This is probably related to #32 and [raspberrypi/pico-feedback#134](https://github.com/raspberrypi/pico-feedback/issues/134)
> Unfortunately VS Code support is a low-priority task that we've not had enough spare time to deep-dive into.
> 
> It _should_ still work if you build from the command-line though?

Thanks for feedback
