### ISSUE TITLE
Predefined path to GCC for arm-none-eabi tools

### ISSUE THREAD

**Issue by ms1963** [raspberrypi/pico-project-generator#34]
When asking the Pico Project Generator to create output for Visual Studio Code, the generator assumes, the location of these tools is /usr/bin/...... This is statically defined in the Python code.

Proposal: either introduce a command line argument for passing the path or let users specify this path in a configuration file.

**Comment by lurch** [comment]
Tangentially related to https://github.com/raspberrypi/pico-sdk/issues/258 ?

**Comment by JamesH65** [comment]
Fixed on master.  6f2b85fcf85dae3f302d7815fefa0730a6ec1a60
