### ISSUE TITLE
Issue with generation of the CMakeLists.txt file

### ISSUE THREAD

**Issue by joshuag1000** [raspberrypi/pico-project-generator#4]
When CMakeLists.txt is generated quotes are not inserted before and after the path meaning that if there is a space in the SDK path cmake fails to generate the build files.

I have submitted a pull request with a fix for this bug.

**Comment by joshuag1000** [comment]
https://github.com/raspberrypi/pico-project-generator/pull/3

**Comment by JamesH65** [comment]
Thanks, will take a look on Monday. There's going to be a number of things like this, so be prepared!

**Comment by joshuag1000** [comment]
Yeah i can imagine! all i did was just add one line and it seems to work fine for me.

**Comment by JamesH65** [comment]
Fix merged. Thanks!
