### ISSUE TITLE
pico_sdk_import.cmake not found

### ISSUE THREAD

**Issue by AlexChadwickP** [raspberrypi/pico-project-generator#45]
the generator can't seem to find pico_sdk_import.cmake for some reason although I've checked the path and it does exist. I'm running this from an WSL Ubuntu in Windows 11, here's a screenshot of the output and of the `ls` of the directory it's looking in:
![image](https://user-images.githubusercontent.com/42715369/143918037-9dee5f40-c571-4906-83f7-6ae4043b8a10.png)

**Comment by joshuag1000** [comment]
i could be wrong but it looks like your pico path is set to ../pico-sdk try setting it to the exact path of where your pico sdk is.

**Comment by AlexChadwickP** [comment]
> i could be wrong but it looks like your pico path is set to ../pico-sdk try setting it to the exact path of where your pico sdk is.

Yes, that was the problem, silly mistake from me, thanks!
