### ISSUE TITLE
runToMain should be runToEntryPoint in generated VSCode launch.json

### ISSUE THREAD

**Issue by marktyler72** [raspberrypi/pico-project-generator#49]
The launch.json file that is generated if Create VSCode Project is selected contains a line:
~~~
   "runToMain": true,
~~~

The runToMain option has been depreciated in Cortext-Debug for VSCode since v0.3.12 and been replaced with runToEntryPoint.  
So the line in launch.json should be:
~~~
    "runToEntryPoint": "main",
~~~

**Comment by JamesH65** [comment]
Fixed
