### ISSUE TITLE
bug: Scan for local boards. 

### ISSUE THREAD

**Issue by rewolff** [raspberrypi/pico-project-generator#60]
I have set: 
  PICO_BOARD_HEADER_DIRS
so that builds will now find my own RP2040 based boards. 

It'd be nice if the pico-project-generator would scan the listed directory and add the boards there to the list of available boards. 

(not sure how the current list is generated, but that should be generated at runtime from $PICO_SDK/src/boards/include/boards/ ... )

**Comment by JamesH65** [comment]
Hi, I think I have already done this, there is a branch with the change, so you are welcome to try it out. In fact, I've been waiting for people to report on it, but nothing so far!

https://github.com/raspberrypi/pico-project-generator/tree/pico-w-support

**Comment by rewolff** [comment]
Oh.... I'm on the pico-w-support branch, and I didn't see my boards.... So now this turns into a bug report :-)

**Comment by JamesH65** [comment]
Hmm, thought I simply scanned the boards folder and displayed the content but I wrote it a couple of months ago so may be misremembering.

**Comment by JamesH65** [comment]
Ah, I just scan the SDK's boards folder, not the PICO_BOARD_HEADER_DIRS folder. Mainly because I had not heard of PICO_BOARD_HEADER_DIRS. That is a bug, so please feel free to create a new issue.

**Comment by rewolff** [comment]
What's wrong with this one?

**Comment by JamesH65** [comment]
Nothing wrong with this one, Covid brain fart! Just change the title.

**Comment by JamesH65** [comment]
This should now be fixed on top of tree master.
