### ISSUE TITLE
Missing quotes

### ISSUE THREAD

**Issue by soonuse** [raspberrypi/pico-project-generator#65]
In pico_project.py, line 1169
`f'      "compilerPath": {compilerPath},\n'`
compilerPath without quotes makes VSCode error: Failed to parse ".vscode/c_cpp_properties.json": Unexpected token /

Adding quotes will fix the error, i.e.
`f'      "compilerPath": \"{compilerPath}\",\n'`

**Comment by JamesH65** [comment]
Oops, bad testing on my part. Will fix Monday, or you can provide a PR that I will merge Monday.

**Comment by soonuse** [comment]
Thank you for fixing it :D

**Comment by soonuse** [comment]
Oops, typo in my comment. There is no need to add backslashes in Python. (\"  --> ")

**Comment by JamesH65** [comment]
Pushed a fix to master.
