### ISSUE TITLE
Various issues when "Location" is not set in GUI

### ISSUE THREAD

**Issue by nochkin** [raspberrypi/pico-project-generator#9]
When I leave "Location" field empty in GUI, I get a confusing error in the console:
`FileNotFoundError: [Errno 2] No such file or directory: 'ProjectName/pico_sdk_import.cmake'`

Additionally, when "Location" is empty, the `pico_project.py` will not properly validate if the "Project Name" directory exists.

**Comment by nochkin** [comment]
I just created PR #10 to address it. It sets the current directory into "Location" field in the GUI on a start up.

**Comment by JamesH65** [comment]
Fixed by the linked PR. Thanks!
