### ISSUE TITLE
[windows] invalid compilerPath in c_cpp_properties.json

### ISSUE THREAD

**Issue by ychsiao168** [raspberrypi/pico-project-generator#99]
platform: win11

command: python pico_project.py --gui and "Create VSCode project" is checked.

line 10 in c_cpp_properties.json: 
```bash
"compilerPath": "C:\Program Files\Raspberry Pi\Pico SDK v1.5.1\gcc-arm-none-eabi\bin\arm-none-eabi-gcc.EXE",
```

currently I just modify '\\' to '\\\\' and everything is ok 

<img width="1139" alt="image" src="https://github.com/raspberrypi/pico-project-generator/assets/571953/a7005e53-ca86-4226-a5bb-c9d1e2063ddf">

**Comment by lurch** [comment]
Duplicate of #67 ? ping also @ndabas as it looks like you're using the Windows Pico Setup program.

**Comment by ychsiao168** [comment]
> Duplicate of #67 ? ping also @ndabas as it looks like you're using the Windows Pico Setup program.

yes same as #67 and I'm using Windows Pico Setup program.

if I use 'update_vscode_json_to_sdk1_5' branch, compilerPath is ok.
